
CREATE TEMP FILE FORMAT "MYTESTDB"."MYTESTSCHEMA"."my_json_format_new"
	TYPE=JSON
    STRIP_OUTER_ARRAY=FALSE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "MYTESTDB"."MYTESTSCHEMA"."BRAND_TEST" 
FROM (SELECT $1:_id::VARCHAR, $1:barcode::VARCHAR, $1:brandCode::VARCHAR, $1:category::VARCHAR, $1:categoryCode::VARCHAR, $1:cpg::VARCHAR, $1:name::VARCHAR, $1:topBrand::BOOLEAN
	FROM '@"MYTESTDB"."MYTESTSCHEMA"."MY_STAGE_BRANDS"') 
FILES = ('brands.json') 
FILE_FORMAT = '"MYTESTDB"."MYTESTSCHEMA"."my_json_format_new"' 
--MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE
ON_ERROR=ABORT_STATEMENT 
